### ISSUE TITLE
Draco mesh and file export support

### ISSUE THREAD

**Issue by orangeagain** [atteneder/DracoUnity#1]

**Comment by atteneder** [comment]
Hi,
currently you cannot create Draco meshes or files (.drc) from within Unity (not at runtime nor in the Editor). It's a valid request though,.

Please use the command line tool from the [official draco repository](https://github.com/google/draco) to create Draco files.

**Comment by atteneder** [comment]
Added in 2.0.0 (currently in preview). Feel free to test.

**Comment by atteneder** [comment]
@arjungaonkar Right, runtime encoding is not implemented yet (see #56). Help is welcome!
