### ISSUE TITLE
Cannot encode mesh in latest version.

### ISSUE THREAD

**Issue by sam598** [atteneder/DracoUnity#12]
Tried exporting both a GameObject (default sphere) using `Tools > Draco > Encode Selected GameObject` and received this error:

```
InvalidOperationException: The NativeArray can not be Disposed because it was not allocated with a valid allocator.
Unity.Collections.NativeArray`1[T].Dispose () (at <4cc8ec075538416496e5db5d391208ac>:0)
Draco.Encoder.DracoEncoder.EncodeMesh (UnityEngine.Mesh unityMesh, System.Int32 encodingSpeed, System.Int32 decodingSpeed, System.Int32 positionQuantization, System.Int32 normalQuantization, System.Int32 texCoordQuantization, System.Int32 colorQuantization, System.Int32 genericQuantization) (at C:/.../Runtime/Scripts/Encoder/DracoEncoder.cs:234)
Draco.Encoder.DracoEncoder.EncodeMesh (UnityEngine.Mesh unityMesh, UnityEngine.Vector3 worldScale, System.Single precision, System.Int32 encodingSpeed, System.Int32 decodingSpeed, System.Int32 normalQuantization, System.Int32 texCoordQuantization, System.Int32 colorQuantization, System.Int32 genericQuantization) (at C:/.../Runtime/Scripts/Encoder/DracoEncoder.cs:104)
Draco.Editor.DracoEditorEncoder.CompressMeshFilters (UnityEngine.MeshFilter[] meshFilters, System.String directory) (at C:/.../Editor/DracoEditorEncoder.cs:151)
Draco.Editor.DracoEditorEncoder.Compress () (at C:/.../Editor/DracoEditorEncoder.cs:88)
```

Tried exporting a mesh (read/write enabled obj in assets) using `Tools > Draco > Encode Selected Mesh` and received this error:

```
InvalidOperationException: The NativeArray can not be Disposed because it was not allocated with a valid allocator.
Unity.Collections.NativeArray`1[T].Dispose () (at <4cc8ec075538416496e5db5d391208ac>:0)
Draco.Encoder.DracoEncoder.EncodeMesh (UnityEngine.Mesh unityMesh, System.Int32 encodingSpeed, System.Int32 decodingSpeed, System.Int32 positionQuantization, System.Int32 normalQuantization, System.Int32 texCoordQuantization, System.Int32 colorQuantization, System.Int32 genericQuantization) (at C:/.../Runtime/Scripts/Encoder/DracoEncoder.cs:234)
Draco.Editor.DracoEditorEncoder.EncodeMesh (UnityEngine.Mesh mesh, System.String directory) (at C:/.../Editor/DracoEditorEncoder.cs:225)
Draco.Editor.DracoEditorEncoder.EncodeSelectedMeshes () (at C:/.../Editor/DracoEditorEncoder.cs:213)
```

Also received this error sporadically afterwards:

```
A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.
```

Same error appeared both when installed using ` Install-com.atteneder.draco-2.0.0-preview.unitypackage` as well as pulling the latest source from github.

**Comment by sam598** [comment]
Using Unity 2020.1

**Comment by atteneder** [comment]
Hi @sam598,

Thanks for reporting. Are you using the GIT repository or the package from OpenUPM?

I'm on paternity leave, but I'll try to look into in ~2 weeks.

**Comment by sam598** [comment]
Congratulations!


I had the same result using the unitypackage located here: https://package-installer.glitch.me/v1/installer/OpenUPM/com.atteneder.draco?registry=https%3A%2F%2Fpackage.openupm.com&scope=com.atteneder

As well as the pulling the GIT repository and installing it as a local package with the Unity package manager.

I was able to get it to work with Unity 2021.3.1f1

**Comment by YeonduBori** [comment]
Can i ask you something? @sam598
How did you build `dracoenc_unity,dll`? I can't find that dll file in draco unity
I got Error at [DllImport("dracoenc_unity")] 
I got same issue 
`A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.`

**Comment by atteneder** [comment]
> Can i ask you something? @sam598
> How did you build `dracoenc_unity,dll`? I can't find that dll file in draco unity
> I got Error at [DllImport("dracoenc_unity")]
> I got same issue
> `A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.`

You shouldn't need to build the binaries yourself. This project uses GIT LFS for dll files, so please make sure you have GIT LFS installed when cloning this repository.
Otherwise, the binaries are built in this [GitHub project's actions](https://github.com/atteneder/draco/actions/runs/625090681).

**Comment by atteneder** [comment]
I couldn't reproduce on 2020.3 LTS nor 2021.1.
It makes no sense to me to spend time fixing it for 2020.1, so please upgrade to 2020.3 LTS and see if this solves your problem (reopen and provide steps to reproduce otherwise).

Thanks!
