### ISSUE TITLE
Don't Remove Coroutine Functionality In 2.0

### ISSUE THREAD

**Issue by DerrickBarra** [atteneder/DracoUnity#13]
Hi @atteneder , I noticed on your 2.0 preview package that you remove the coroutine functionality and switch to solely using the async. Our team uses GLTFUtility with DracoUnity on WebGL which needs Coroutine Compatability (WebGL is single-threaded and has issues with async + multithreading). Could you leave the coroutine functionality in place and then add the async option as well?

**Comment by atteneder** [comment]
Hi @DerrickBarra,

Thanks for your patience. Do you have actual troubles with async or is it just that you'd prefer a coroutine based API?

To my knowledge async on WebGL is only a problem if you use it in a threaded way. I'd have to make sure this is not the case for DracoUnity.

I could provide a coroutine wrapper around the async method, but I don't see much of a benefit (other than convenience to users).

Let me know what you think

**Comment by DerrickBarra** [comment]
@atteneder It would be for convenience and not having to break plugin compatability. The GLTFUtility plugin version our team is using is all on coroutines, so having access to a coroutine version of DracoUnity is needed for us to upgrade to the latest.

**Comment by Blocovin** [comment]
@DerrickBarra You can use the great [UnitTask](https://github.com/Cysharp/UniTask) plugin. "UniTask.ToCoroutine" bridges async/await to coroutine.

**Comment by DerrickBarra** [comment]
@Blocovin good to know about UniTask. I'm trying to keep my build size down for WebGL export as much as possible, but I'm happy to know there's an alternative solution if it comes down to it!

**Comment by atteneder** [comment]
Fair enough.
I'll provide legacy Coroutine wrappers to not break anything in the 2.x release.
Thanks for the feedback!

**Comment by atteneder** [comment]
Since I didn't have time for convenience stuff the last month, I reconsidered to not fix this.

Please wrap it yourself or use [glTFast](https://github.com/atteneder/glTFast).
