### ISSUE TITLE
update 2.0.0-preview tag?

### ISSUE THREAD

**Issue by benvvalk** [atteneder/DracoUnity#15]
Hi @atteneder!

I'm currently testing DracoUnity with my [Piglet glTF importer](https://assetstore.unity.com/packages/tools/utilities/piglet-gltf-importer-173425) project, and so far it is working fantastically.  (Thanks for yet another awesome unity package!)

I was wondering if you could update the `2.0.0-preview` tag to point to the latest commit (i.e. 23519d3) on `master`?

I noticed that the current `2.0.0-preview` commit (8d2ca67) produces a compile error in Unity 2019.3.13f1 (and probably any Unity version < 2020.2.x), due to use of the `??=` operator.  But it looks like you've already fixed that issue in eeacd3e.

You may have other reasons for not updating the `2.0.0-preview` tag yet (e.g. untested/unsafe changes). If that's the case, no problem -- I will just advise my users to use DracoUnity 1.4.0 for the time being.  Updating the `2.0.0-preview` tag would be better, though, because then the installer link from README.md would work as expected in Unity 2019.3+.

**Comment by atteneder** [comment]
Hi @benvvalk,

Thanks for your interest.

I am holding back 2.x because I have to fix a remaining issue with skinning. I also don't want to re-tag the same tag name to avoid confusion. Not sure if a `2.0.0-preview-1` would work with UPM? Would you know by chance?

For now I'd stay with 1.4.0, but I try to catch up soon.

**Comment by benvvalk** [comment]
@atteneder,

No problem and thanks for your reply.

Fair enough about not wanting to cause confusion by changing the commit for an existing tag.  That's probably a wise policy, even for "preview" tags. FYI, it looks like UPM would accept a tag of the form `v2.0.0-preview.1`.  From the docs (https://openupm.com/docs/adding-upm-package.html#upm-package-criteria):

> The package should contain versioned Git tags using semantic versioning (semver) . i.e. v1.1.0, 1.1.0, 1.1.1-preview, v2.0.0-preview.1. It's recommended to either use the GitHub release page, or the CI tools to create versioned Git tags.

But I haven't tried it myself.

I will include the HEAD version (23519d3) in my Piglet integration testing (in addition to DracoUnity 1.4.0), and let you know if I hit any issues.
