### ISSUE TITLE
point cloud support in 2.0.0

### ISSUE THREAD

**Issue by lauretao08** [atteneder/DracoUnity#16]
Hello,

First of all, Thank you for your extension of the Draco functionnality for Unity. I was using it in projects and I realized that, while the performance is quite impressive, whenever I tried to load draco-compressed point clouds it would not work natively, returning the error : "Failed: Decoding error".

Then i saw the work [camnewnham](https://github.com/camnewnham) and you did [here ](https://github.com/atteneder/glTFast/issues/135) to try and implement point cloud support in these tools. Hence, I wondered if you planned to implement support of point clouds in the upcoming 2.0.0 version ? Or, in the case it would not be planned, if trying to implement the features discussed above in the new version when it is released ?

Thanks.

**Comment by atteneder** [comment]
Hello,

now that 2.0.0 and 3.0.0 are done and out I want to give a comment.

I briefly looked into loading point clouds and figured this requires changes from the native library up to the C# integration, much like the work @camnewnham already did on the old version.

I still agree this would be a great feature, but I couldn't fit it into 2.x/3.x. So the timeline is still uncertain, unless someone else picks it up sooner than me.

Thanks for your interest!

**Comment by lauretao08** [comment]
Hi,

Thank you for the heads-up. If I find the time in the meanwhile I will look into it and see if the work done can be translated to the latest version. I'll try to post news if I manage to make some progress.

**Comment by camnewnham** [comment]
@lauretao08 just letting you know that point cloud support has been added and released in v3.3.0+

**Comment by atteneder** [comment]
Works in 3.3.0+
