### ISSUE TITLE
Draco breaks the geometry of long objects

### ISSUE THREAD

**Issue by NeluQi** [atteneder/DracoUnity#20]
After Draco squeezed, the geometry of the long objects broke.
Used gltf-transform for compression

![image](https://user-images.githubusercontent.com/16963395/119712856-b906b480-be69-11eb-8e27-9df50d4e6231.png)

![image](https://user-images.githubusercontent.com/16963395/119713395-53ff8e80-be6a-11eb-9524-b17a4f14d66f.png)

in glTFast 4.0.0 loaded in glb format

I will attach the original and compressed models
https://drive.google.com/file/d/1lGL_0los-PoSkNo7xAWK08aJOWElC2J0/view?usp=sharing

**Comment by atteneder** [comment]
Draco compression is lossy. The quantization of positions might cause this. Did you test it another viewer (like the [glTF-Sample-Viewer](http://gltf.ux3d.io/)) ?

**Comment by atteneder** [comment]
If it's also broken there, the draco compression parameters (about quantization) maybe wrong and have to be adjusted. Contact gltf-transform devs in that case.

**Comment by atteneder** [comment]
DracoUnity for example adjust quantization parameters to the overal size in the szene. Bigger objects get more details (higher quantization).

**Comment by NeluQi** [comment]
You are right, in the other viewers the geometry is broken

![image](https://user-images.githubusercontent.com/16963395/119717477-05082800-be6f-11eb-8bcb-21ab2758b195.png)

**Comment by atteneder** [comment]
Having the experience of integrating the Draco encoder is valuable in that case :)

**Comment by atteneder** [comment]
Solutions suggestion:

Break up the mesh into smaller sections. Sections should be more equal sized in each axis (close to a cube than a longish cuboid)
