### ISSUE TITLE
skinned mesh loading errors with DracoUnity 2.x/3.x

### ISSUE THREAD

**Issue by AwesomesauceLabs** [atteneder/DracoUnity#21]
Hi @atteneder!

Unfortunately, I'm experiencing some issues when loading skinned meshes with DracoUnity 3.0.2 (Unity 2020.3.9f1).

The loaded bone indices/weights data seem to be incorrect/uninitialized, and in addition I am seeing the following error in the Unity console:

![dracounity-error](https://user-images.githubusercontent.com/53091896/119719065-51834180-be36-11eb-8dbc-777536362eb7.png)

Sorry about the lack of stack trace, btw.  So far I can't figure out how to "Enable Full StackTraces to get more details."  I know there's supposed to be an item in the Unity "Jobs" menu to do that, but I don't see it.  (Frustrating!)

# Minimal Test Case

I created a minimal project to reproduce the issue by:

1. Forking your [DracoUnityDemo](https://github.com/atteneder/DracoUnityDemo) project.
2. Adding a Draco-compressed version of the [RiggedSimple](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedSimple) model as `StreamingAssets/RiggedSimple.drc`.
3. Changing `DracoDemo.cs` code to load the model with (hopefully) correct parameters.

You can get my test case by cloning https://github.com/AwesomesauceLabs/DracoUnityDemo. (It's the HEAD commit on the `main` branch.)

# Creating RiggedSimple.drc

`RiggedSimple.drc` is included in https://github.com/AwesomesauceLabs/DracoUnityDemo, but since creating the file was tricky, I wanted to document the steps here:

```sh
# clone the sample models
git clone git@github.com:KhronosGroup/glTF-Sample-Models.git

# This directory contains: RiggedSimple.gltf, RiggedSimple0.bin
cd glTF-Sample-Models/2.0/RiggedSimple/glTF

# make a subdir for the Draco-compressed glTF file
mkdir Draco
cp * Draco
cd Draco

# Draco-compress the glTF file.
# This generates a new RiggedSimple0.bin, which contains both the
# uncompressed animation data and the Draco-compressed mesh data.
gltf-transform draco RiggedSimple.gltf RiggedSimpleDraco.gltf

# Extract the Draco blob from RiggedSimple0.bin.
# I had to look through RiggedSimpleDraco.gltf to determine the
# correct `skip`/`count` values.
dd iflag=skip_bytes,count_bytes skip=2328 count=1000 if=RiggedSimple0.bin of=RiggedSimple.drc
```

# Expected Bone Indices/Weights vs. Observed Bone Indices/Weights

Expected: [bone-weights-standard.tsv.txt](https://github.com/atteneder/DracoUnity/files/6549392/bone-weights-standard.tsv.txt)
Observed: [bone-weights-draco.tsv.txt](https://github.com/atteneder/DracoUnity/files/6549393/bone-weights-draco.tsv.txt)

**Comment by atteneder** [comment]
Hi @AwesomesauceLabs ,

Thanks for reporting!

Does the original RiggedSimple asset with draco (and all other glTF-Sample-Models with Draco) work for you or is it just this gltr-transform compressed one? Because with glTFast+DracoUnity 3.0.2 those seem to work just fine.

**Comment by AwesomesauceLabs** [comment]
@atteneder,

Ha, somehow I completely missed that the glTF-Sample-Models repo already provides a Draco version of RiggedSimple!

But yes, I still get the same error even when I load the Draco version provided by the glTF-Sample-Models repo.  I tried it with both Piglet 1.3.0 and DracoUnityDemo.  (For DracoUnityDemo, I had to extract the `.drc` file from the `.bin` with `dd` again.)

Very interesting that the error doesn't happen in glTFast, but that it does happen in Piglet and DracoUnityDemo!

I'm testing on Windows 10, btw.  Are you by any chance testing on MacOS or Linux? What Unity version are you using?

**Comment by atteneder** [comment]
Developing on mac mainly, but I just tested and confirmed that RiggedSimple works on Windows as well.

**Comment by atteneder** [comment]
What I'd do in your case:

Set debug points in `DracoMeshLoader.ConvertDracoMeshToUnity` in both glTFast and Piglet and compare the input parameters. Also the first/last couple of bytes from the data.

hth

**Comment by AwesomesauceLabs** [comment]
Sounds like a good idea.  I'll give that a try tomorrow (thanks!).

**Comment by AwesomesauceLabs** [comment]
Hi @atteneder,

I found the problem!

I did as you suggested and compared the binary data and parameters used by glTFast vs. my forked DracoUnityDemo project. Both the binary data and the method arguments matched up, so I didn't make any mistakes there.

The crucial difference was that I was using the `ConvertDracoMeshToUnity` method that takes a C# `byte[]`, whereas glTFast was calling the `ConvertDracoMeshToUnity` method that takes a `NativeSlice<byte>`.  It seems that the wrapper `byte[]` method does not work as intended.

When I create/dispose my own `NativeArray<byte>` and then use the `NativeSlice<byte>` version of the method instead, the bone weight data gets loaded correctly and there are no errors.

**Comment by atteneder** [comment]
Hi @AwesomesauceLabs,

I've had time to look at it today. Do you, by chance, utilize the `MeshData` variant of `ConvertDracoMeshToUnity`? Because if yes, you'll notice it returns a `DecodeResult` (instead of a `Mesh`). If that `DecodeResult`'s `boneWeightData` is not null, you'll have to take care of applying and disposing it yourself. This would explain the undisposed NativeArray errors you get.

The DracoUnityDemo didn't do this as well, so I fixed it with something like this:

```csharp
if (results[i].boneWeightData != null) {
    results[i].boneWeightData.ApplyOnMesh(mesh);
    results[i].boneWeightData.Dispose();
}
```

Please let me know if that was your problem as well.

**Comment by AwesomesauceLabs** [comment]
Thanks for your help, @atteneder!

Yes, you are right and it was my error.  I misread your code and I failed to notice that some of the method signatures for `ConvertDracoMeshToUnity` are different in Unity 2020.2+ (due to `#if`/`#else` blocks).

Thanks also for adding the `DracoDemoMeshData.cs` example to the `DracoUnityDemo` repo. I think that example may be a very helpful reference in the future, since I am not yet familiar with `MeshData` and the "Advanced Mesh API".

For now, I will stick to using the `ConvertDracoMeshToUnity` method that takes a `NativeSlice<byte>` as input, since that method is straightforward to use and is available across all Unity versions.  (So far it is working well, although I still have a bit more testing to do.)

Closing the issue now.

**Comment by atteneder** [comment]
> Yes, you are right and it was my error. I misread your code and I failed to notice that some of the method signatures for `ConvertDracoMeshToUnity` are different in Unity 2020.2+ (due to `#if`/`#else` blocks).

@AwesomesauceLabs , I respectfully disagree about you having made an error or me being "right" (which is not important at all) :)

In this case the lack of documentation made you use it incorrectly (I cannot expect every user to read the source). To me, that's an error. I've added documentation now and hope it's clearer now.

Thanks for your valuable feedback!

**Comment by AwesomesauceLabs** [comment]
Thanks for the kind words, @atteneder :-)

I think the notes/code you added to the README.md are quite helpful, so thanks for that too.
