### ISSUE TITLE
Vertex colors don't load

### ISSUE THREAD

**Issue by camnewnham** [atteneder/DracoUnity#27]
# Description
I've been working on #16 and run into an issue where vertex colors don't load either for meshes or point clouds.

The vertex attribute descriptors appear correct:
 `VertexAttribute=Color,
VertexAttributeFormat=UInt8,
numComponents=4,
elementSize=4` 

Attempting to access `unityMesh.colors` results in:
```
Unsupported conversion of vertex data (format 6 to 0, dimensions 4 to 4)
UnityEngine.Mesh:get_colors ()
```
If the resulting array (from `unityMesh.colors`) is read the results are all rgba(0,0,0,0), hence the black.

This applies to both point clouds (in my WIP implementation) and meshes (in `main`)

There's minimal discussion of MeshData online, but I did see [this ](https://forum.unity.com/threads/needs-some-eyes-on-this-please.851425/)which suggests it could be a Unity issue.

Colors _do_ load correctly in `GLTFast` when models are not draco compressed.

# Environment
Unity 2020.3.15f2
DracoUnity `main` https://github.com/atteneder/DracoUnity/commit/9f5161b5eec0c99425ec0e207ec1e7df5eea5cd1

# Expected Behaviour
In three.js:
![image](https://user-images.githubusercontent.com/19278856/128130828-883968bb-c7b9-425f-9af5-d928490f842c.png)
Point Cloud (vertex colors) on left, Mesh (vertex colors) in center, Mesh (no colors) on right.
# Actual Behaviour
In GLTFast/DracoUnity:
![image](https://user-images.githubusercontent.com/19278856/128133198-476c9d70-f4e4-4d50-b23b-4c69b0fc26c7.png)

**Comment by camnewnham** [comment]
Here is an example file for reproduction:

[bunny_mesh_color.zip](https://github.com/atteneder/DracoUnity/files/7146488/bunny_mesh_color.zip)
The regular .glb works correctly. The draco compressed .glb does not load colors in glTFast/Unity

In threejs:
![image](https://user-images.githubusercontent.com/19278856/132917388-7a11fff3-188a-4eb1-b280-21a7ac54c2a2.png)

In Unity/glTFast:
![image](https://user-images.githubusercontent.com/19278856/132917503-dd3fffb7-0743-485d-989a-2764e724c51e.png)

**Comment by atteneder** [comment]
first suspicion: Unity cannot work with uint8 vertex colors.

**Comment by atteneder** [comment]
> first suspicion: Unity cannot work with uint8 vertex colors.

confirmed! I hacked in a uint8->float conversion and  then it's correct:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/2593014/132955457-ec5cb1a9-cfe0-4c31-bcf5-840176515bb1.png">

Next steps:

- Figure out if it's even possible to render non-default data types with existing shaders (for colors, but all other vertex attributes as well)

If not:

- Convert incompatible data types into compatible ones in a Job in C#

The "if not" part, unfortunately, is quite some work.

Easy workaround should be to encode colors as floats (untested)

**Comment by atteneder** [comment]
As it turned out, Unity *can* work with normalized uint8 colors, if you properly declare them as `VertexAttributeFormat.UNorm8` (instead of `VertexAttributeFormat.UInt8`)

@camnewnham I'll release this fix soonish, but would appreciate if you could run a quick test with current main branch. Thanks!

**Comment by benvvalk** [comment]
Thanks so much for the fix, @atteneder! I have a Piglet customer who is having the same issue (no vertex colors in their Draco-encoded model).

I'll test the HEAD version of DracoUnity with Piglet and let you know if it works!

**Comment by benvvalk** [comment]
It works!

I just confirmed that the vertex colors load correctly in Piglet using the HEAD DracoUnity version. I tested with Unity 2020.3.9f1, using the bunny model above and also with the example model that my customer shared privately.

**Comment by camnewnham** [comment]
Thanks @atteneder, good find!
Confirming that this works for us.

**Comment by JamWils** [comment]
I know this is old, but thank you for the fix!  I had `UInt8` and was wondering why they were all black.  `UNorm8` made sure all of the vertex color data was passed to the new mesh data I was building.
