### ISSUE TITLE
Unity Plugin Source

### ISSUE THREAD

**Issue by onehundredfeet** [atteneder/DracoUnity#29]
Hi,

I can't seem to find the source for the unity plugin that matches the code signature of the C# file.

	[DllImport(DRACODEC_UNITY_LIB)]
	private unsafe static extern int DecodeMeshForUnity(void* buffer, int length, DracoToUnityMesh** tmpMesh, int weightsId = -1, int jointsId = -1);

I've looked in the official depot and your forked depot.  And I can't find the weighting version.

Is there somewhere else I should be looking?

Cheers,

Great work by the way.

**Comment by onehundredfeet** [comment]
The only one I can find is:

int DecodeMeshForUnity(char *data, unsigned int length,
                       DracoToUnityMesh **tmp_mesh) {

**Comment by atteneder** [comment]
I'm using my altered fork of the draco project:

https://github.com/atteneder/draco

The most recent GH action build is this one:

https://github.com/atteneder/draco/actions/runs/985769964

hth
