### ISSUE TITLE
Usecase recommendation

### ISSUE THREAD

**Issue by tex447** [atteneder/DracoUnity#3]
Hello @atteneder, I have a Unity WebGL app that users upload OBJ's through and the app will save them to mongoDB for future retrieval by the app/other users. On average the OBJ's are 300kb to 1-2MB each and when a user is fetching a set from the database through the unity app, on average are pulling 2-5MB of payload. 

Do you think compressing with Draco as the user submits the OBJ's will help with load times when other users fetch the model sets?

**Comment by atteneder** [comment]
Hi @tex447,

Absolutely!

First of all, OBJ is a text based format and parsing text is slow. Any binary format will be significantly faster.

On top of that, Draco mesh compression can further reduce the binary size at some cost in form of decoding at runtime. With mobile connection speeds, this cost usually pays off.

There's a difference between OBJ and Draco worth pointing out:
OBJ supports multiple objects, groups and simple materials/textures.
Draco is a pure mesh compression method. If you need any of the above OBJ features as well, you have to take care of those in some way. Consider using a format like glTF-binary (which in itself can make use of Draco mesh compression).

You will have to convert OBJ into glTF first though, either on server-side or on the client directly. This takes some development work and can become complicated.

hth
