### ISSUE TITLE
Error CS0246

### ISSUE THREAD

**Issue by drperpen** [atteneder/DracoUnity#31]
Hi,
I am running Unity 2020.3.4f1 on Windows 10 64-bit, and when I try to run the Installer Package I get the following errors in the console. It looks the installation fails as Draco Unity is not visible in the Package Manager nor I see anything when I open the demo Draco Unity project. These are the 2 error messages:

Assets\Scripts\DracoDemo.cs(18,7): error CS0246: The type or namespace name 'Draco' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\DracoDemoMeshData.cs(22,7): error CS0246: The type or namespace name 'Draco' could not be found (are you missing a using directive or an assembly reference?)

Thanks!
Daniel

**Comment by atteneder** [comment]
Read the README.md regarding installing locally and look out for the GIT LFS section

**Comment by drperpen** [comment]
I installed GIT LFS on my machine and now when I open the project that had Draco 3.2.0 I see the package downgraded itself to 1.4.0

![image](https://user-images.githubusercontent.com/51986483/131234263-b75c0282-911c-4d58-8e70-1c5ed5dcdc07.png)

**Comment by atteneder** [comment]
According to this screenshot you don't have the local version installed, but the one from the scoped registry (hence my name's at the top). Note: this can happen when you change versions!

Click the plus icon to add the local `package.json` again.

To check if GIT LFS is correct now: See if the binary files (like the `.dll` file) is bigger than just a couple of bytes.

**Comment by drperpen** [comment]
I reinstalled from package.json and now I have 3.2.0 again. Git LFS is installed and initilized but this method is still not working. So I ended up downloading the .dll files manually and reinstalling 3.2.0 and now it's working.

Thanks for your help!
