### ISSUE TITLE
Build issues in 2021.2.0b9

### ISSUE THREAD

**Issue by Bersaelor** [atteneder/DracoUnity#32]
So, I was trying to build the project in beta 9 for WebGL, getting this error:

```
emcc2: error: Packages/com.atteneder.draco/Runtime/Plugins/WebGL/libdracodec_unity.a: No such file or directory ("Packages/com.atteneder.draco/Runtime/Plugins/WebGL/libdracodec_unity.a" was expected to be an input file, based on the commandline arguments provided)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:179)
```

First happened in my main project, then also tried after freshly importing gltFast and Draco into a new project in a simple test project.

(First tried `4.0.0-preview.1` then `4.0.0-preview.3` both with the same error)

**Comment by Bersaelor** [comment]
Ran another test with a minimal sample project, in `2021.1.17f1` it successfully built for WebGL.

When I then upgrade the project to `2021.2.0b9`I get the error again
```
emcc2: error: Packages/com.atteneder.draco/Runtime/Plugins/WebGL/libdracodec_unity.a: No such file or directory ("Packages/com.atteneder.draco/Runtime/Plugins/WebGL/libdracodec_unity.a" was expected to be an input file, based on the commandline arguments provided)
```

The thing is that the file itself is definitely there. I wonder if this is a problem in the Draco project setup or a bug in Unity beta 2021.2 ?
In the latter case we should probably make a Bug report to Unity?

**Comment by atteneder** [comment]
Hi @Bersaelor ,

There's a similar build [problem in KtxUnity](https://github.com/atteneder/KtxUnity/issues/43)

Unity 2021.2 beta uses a newer version of Emscripten, which changed the way of static linking and there seems to be a bug about that.

**Comment by Bersaelor** [comment]
Ah dang it, we just managed to build the workaround for the issue described in https://forum.unity.com/threads/fails-to-compile-on-webgl-platform-contain-native-plugin-files-bc.1137496/#post-7381241are

**Comment by atteneder** [comment]
@Bersaelor sorry to hear you ran into the next obstacle, but that tip/workaround is great info. Thanks!

**Comment by TeryBuster** [comment]
Hi , I have similar Error with WebGL build...
it works in editor but in WebGL Build is'nt work
is there any tips to solve this problem?

Errors//
missing function: DecodeDracoMeshStep1

NullReferenceException: Object reference not set to an instance of an object.
  at Draco.DracoNative.CreateMesh (System.Boolean& calculateNormals, System.Boolean requireNormals, System.Boolean requireTangents, System.Int32 weightsAttributeId, System.Int32 jointsAttributeId, System.Boolean forceUnityLayout)...

//Errors
Draco Asset version : 4.0.0-preview.3
Unity version: 2021.1.17f1 , 2020.3.11f1 , 2020.3.17f1
Browser: chrome , firefox

**Comment by Bersaelor** [comment]
@TeryBuster that error seems to be specific to your mesh, the issue in this thread is more about that in `2021.2.0b9` a project with Draco doesn't build at all, so I don't even get to try anything (due to changes in the Unity 2021 beta build).
In `2021.1.17f1` and before the package itself seemed to build and my simple test meshes also worked.

In a different scenario I had, it helped @atteneder to have the actual test mesh that causes the error, so he can debug it.

**Comment by atteneder** [comment]
I just tested and successfully built with DracoUnity 4.0.0-preview.3 and Unity 2021.2.0b11. You have to use version 4 or later for 2021.2 or later!

If you installed via GIT URL or cloned the DracoUnity repository and added the package locally, please make sure you followed the [GIT LFS install instructions](https://github.com/atteneder/DracoUnity#installing).

`DracoUnity/Runtime/Plugins/WebGL/libdracodec_unity.a` has to have ~6.7MB, otherwise it won't work.

Feel free to re-open if the issue persists

**Comment by Bersaelor** [comment]
worked with `2021.2.0b12` didn't have time to test the 11.
