### ISSUE TITLE
WebGL build fails for 2021 and 2022

### ISSUE THREAD

**Issue by PTC-sradlwimmer** [atteneder/DracoUnity#35]
<h1>Background:</h1>

When upgrading from Unity `2020.3.13` to `Unity 2021.2.2` I ran into the following error when building for WebGL:

```
Building Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.js failed with output:
wasm-ld: error: Library/PackageCache/com.atteneder.draco@ebaf8e7e6f/Runtime/Plugins/WebGL/libdracodec_unity.bc: machine type must be wasm32 or wasm64
emcc2: error: '/Applications/Unity/Hub/Editor/2022.1.0a13/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/llvm/wasm-ld @/var/folders/kb/3bv7y1wd3g5b9r0nmdn3cfnc9cdgcz/T/emscripten_w9_luvrm.rsp' failed (1)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

This is also an issue in `Unity 2022.1.0` for WebGL.
Other platforms seem to be working.

<h1>Reproduction:</h1>

1. Install Unity 2021.2.2 with WebGL target
2. Open the `manifest.json` and add

```
"com.atteneder.draco": "https://gitlab.com/atteneder/DracoUnity.git",
```

3. Build for target platform WebGL
4. Build should fail with message

```
libdracodec_unity.bc: machine type must be wasm32 or wasm64
```

<h1>Platforms:</h1>

Affected: Unity 2021.2.2, Unity 2022.1.0
Not affected: Unity 2020.3.13

**Comment by atteneder** [comment]
For Unity 2021.2 and later you have to use DracoUnity 4.x or later.

The recommended way to install is via the installer (see README).

If you insist on installing via GIT URL, please use this one:

`https://github.com/atteneder/DracoUnity.git`

The one you used (gitlab) is outdated and was recently fixed in the readme.

**Comment by rasoulMrz** [comment]
Thanks for your answers, but as mentioned [here](https://github.com/Siccity/GLTFUtility/issues/169) the main problem with the library using the Draco is still unresolved.
Seems that in older versions there was a method with this signature:
```
	[DllImport(DRACODEC_UNITY_LIB)] private static extern int DecodeDracoMesh(
		byte[] buffer, int length, DracoMesh * * mesh);
``` 
Can you provide some information on how this method is changed in newer versions, so we can resolve the issue?

**Comment by atteneder** [comment]
@rasoulMrz I don't know what GLTFUtility is using for Draco. Maybe another version of `draco` (the original Google version?). You have to ask them for support.
