### ISSUE TITLE
Point Cloud Compression

### ISSUE THREAD

**Issue by MoritzSkowronski** [atteneder/DracoUnity#36]
Hi, am I correct in assuming there is no point cloud compression possibility in the current version of DracoUnity? 

If so, do you have any plans on adding it? :)

Cheers

**Comment by atteneder** [comment]
Hi,

I've successfully loaded(decompressed) point clouds, so that should work already. I never tried compressing point clouds (from within Unity). Are you referring to that?

**Comment by MoritzSkowronski** [comment]
Both encoding and decoding within Unity actually. I can only find methods to decode/load meshes. 

Interestingly, I cannot even access the static class `public static class DracoEncode` or its methods like `EncodeMesh`. 

This is on Unity 202.3.22f1 with Draco 4.0.1

**Comment by eric1932** [comment]
> Hi,
> 
> I've successfully loaded(decompressed) point clouds, so that should work already. I never tried compressing point clouds (from within Unity). Are you referring to that?

Can I have a look at your code on how you decompress Draco data to point clouds?

Thanks.
