### ISSUE TITLE
Cannot render such point cloud meshes

### ISSUE THREAD

**Issue by eric1932** [atteneder/DracoUnity#38]
I have a Draco encoded point cloud file named `1.drc`. `DracoMeshLoader` can recognize it as a point cloud file. However, the conversion will fail in `DracoNative.cs:540` with the error of `UNorm8 x 3, data size must be multiple of 4`. I don't get why the color array goes wrong there. I've attached some screenshots as well as the encoded ply file below. Can you help me figure out what's going wrong here? Thank you.

![image](https://user-images.githubusercontent.com/10938293/145695095-a5c4da98-64d1-49f2-ae91-30d5ae29fcec.png)
![image](https://user-images.githubusercontent.com/10938293/145695103-c953e366-4faf-4b09-86be-c4d8adad0683.png)
[1.drc.txt](https://github.com/atteneder/DracoUnity/files/7697900/1.drc.txt)

**Comment by atteneder** [comment]
@eric1932  Thanks for reporting!

I did not test yet, so this is an assumption:

Vertex streams' element size needs to be a multiple of 4 bytes, which is a Unity limitation.

Your color buffer is 3 x 1 byte, which is not compatible. Could you test if using an RGBA buffer (so 4x1 byte) works?

A proper solution would be to detect this problem and add a pad byte automatically somehow.
