### ISSUE TITLE
iOS Simulator support

### ISSUE THREAD

**Issue by AhmadMansy** [atteneder/DracoUnity#44]
As i know that this plugin is not supporting ios simulator, i tried to remove the file from packages with a IPreprocessBuildWithReport script when building for simulator. This way i had success with building my unity project(with glTFast) successfully but of course if the model is compressed with draco it doesn't load.

I also tried to build the file from draco source code using CMake and adding x86_64;arm64 but when it exports two libs one is unity_plugin.a and the other is libdracodec_unity.bundle not .a and both didn't work for me.

is there a chance to support ios simulator as well? 
And if there is a different config for building this library other that this
cmake .. -G Xcode
-DCMAKE_SYSTEM_NAME=iOS
-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.0
-DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
-DBUILD_FOR_GLTF=TRUE
-DDRACO_UNITY_PLUGIN=TRUE

**Comment by atteneder** [comment]
From the CMake docs:

https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html?highlight=ios%20simulator#switching-between-device-and-simulator

I'd like to try it, but not sure if I find time soon.

**Comment by AhmadMansy** [comment]
Ok, thanks
i will give it another try

**Comment by AhmadMansy** [comment]
regarding the iOS simulator binaries, you will include it for ktx (https://github.com/atteneder/KtxUnity/issues/57)
will you do the same here?

**Comment by atteneder** [comment]
> @atteneder Regarding the iOS simulator binaries, you will include it for ktx ([atteneder/KtxUnity#57](https://github.com/atteneder/KtxUnity/issues/57)) will you do the same here?

Very likely, but probably has to wait a bit.

**Comment by AhmadMansy** [comment]
awesome

**Comment by atteneder** [comment]
Is fixed in [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/) (5.0.2; in process of being released).
