### ISSUE TITLE
build fail on iOS arm64

### ISSUE THREAD

**Issue by 625673575** [atteneder/DracoUnity#50]
<img width="452" alt="企业微信截图_9589d623-e81a-4e81-9dac-3d06e93dbea1(1)" src="https://user-images.githubusercontent.com/10473349/179684921-3e0af9a1-7799-4bfe-9f48-6372bcc238a8.png">

I've tried to disable Burst compile, but it doesn't work

**Comment by atteneder** [comment]
It seems like the binary libraries are not getting linked to properly.

Go to the project view and follow this path: `Packages/Draco 3D Data Compression/Runtime/Plugins/iOS`. Within that folder there should be a file named `libdracodec_unity.a`. Certify that it is around 10MB.

If not, chances are you cloned this package manually and did not pull the GIT LFS files properly.

hth

**Comment by akash14darshan** [comment]
@atteneder seems like something happening with xcode 14. i was able to build properly on xcode 13, but cant build it now with xcode14 + ventura

**Comment by AdamFrisby** [comment]
Hi; can reproduce this issue as well - XCode 14.1 (14B47b), will post back if I get a workaround.

**Comment by 625673575** [comment]
> @atteneder seems like something happening with xcode 14. i was able to build properly on xcode 13, but cant build it now with xcode14 + ventura

I guess so, the .a file is manually copied into the Plugins/iOS.But I don't ever try another version of xCode.

**Comment by atteneder** [comment]
I just tried to build the [demo project](https://github.com/atteneder/DracoUnityDemo) successfully using:

- Xcode 14.1 on Ventura
- Unity 2019 LTS
- DracoUnity 3.3.2 installed via OpenUPM

I need more information in order to help you. Maybe try building that project yourself and see if it works there?

**Comment by atteneder** [comment]
No more info, so I assume it was a GIT LFS error and is resolved. Re-open with more info if that's not the case. Thanks!
