### ISSUE TITLE
Make sure DracoUnity doesn't break building to unsupported platforms

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/DracoUnity#51]
Currently, when DracoUnity is in a project it prevents building to a number of platforms:

![image](https://user-images.githubusercontent.com/2693840/191309223-cd868b2b-90f9-49b9-8ba8-63e6e3efd345.png)
(tested with Compilation Visualizer's built-in unit tests)

Would be great if those platforms can be built to (doesn't mean DracoUnity needs to work, just that it properly excludes itself on them)

**Comment by atteneder** [comment]
True. I should also check for KtxUnity.

**Comment by atteneder** [comment]
Is fixed in [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), the successor package.
