### ISSUE TITLE
Memory leak when trying to load invalid data

### ISSUE THREAD

**Issue by chrismeteu** [atteneder/DracoUnity#53]
If you try and decode a file that is not in the Draco format, a memory leak occurs. When working with SLPK files from Esri I was obtaining the geometry bin files. the issue was that not all of them are in the Draco compressed format and therefore when I attempted to decode the file it errored out and caused a memory leak.

**Comment by atteneder** [comment]
Thanks for reporting!

Could you please provide steps how to reproduce the leak?

**Comment by chrismeteu** [comment]
Steps to reproduce. try to load a non-draco compressed file. While passing the wrong file is a bug in my code, draco package creates internal error (since it's on another thread i couldn't get the exact message) and a memory leak occurs

**Comment by atteneder** [comment]
Please transition to [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), the successor of this repository/package. Version 5.0.0 fixed this issue.
