### ISSUE TITLE
Pointcloud is missing Y and Z components

### ISSUE THREAD

**Issue by cuhde** [atteneder/DracoUnity#57]
Hi I am currently testing DracoUnity ([655937b](https://github.com/atteneder/DracoUnity/commit/655937bff22315b4851006ee2b1f9bb93dd19da6)) for live decoding of pointcloud data. For this, I am using newest draco version 1.5.6 on linux with a websocket publisher and decode with DracoUnity.
I am able to encode and decode the data on the sender side and i am able to successfully decode the pcl rabbit drc file in DracoUnity.
But when I try to decode the binary blob from the sender in DracoUnity, I only get a colored line with X values, all Y and Z values stay 0.
Is this a setting that i forgot to sync between the two libraries?
UnityDraco:  
![grafik](https://user-images.githubusercontent.com/36489576/219664917-039a2637-8036-4fb1-9187-00edace2e528.png)  
Sender:
![Screenshot from 2023-02-17 14-26-53](https://user-images.githubusercontent.com/36489576/219665286-68d71b07-e9fb-451c-9082-c4e4ed37fcdd.png)  
There is no error message, ConvertDracoMeshToUnity result.success returns true
Update: same happens with matching draco lib 1.4.1 on sender side.
The attributes are being set correctly on the encoder for x,y,z,rgb with the rgb to rgba fix already applied.
Also the binary blob being sent out has the same length as the one received in unity.

**Comment by cuhde** [comment]
Is there a difference in how draco handles pointclouds and meshes in the compressed format? I just noticed that my encoder calls EncodePointCloudToBuffer and I believe DracoUnity always calls DecodeMeshFromBuffer / DecodeDracoMesh, even if it decodes a PointCloud. Do I need to convert the pointcloud on the sender side to a mesh first and call the mesh encoder in order for this to work?

**Comment by cuhde** [comment]
Ok, I figured it out. The sender was encoding the x,y,z fields in the pointcloud separately as one POSITION attribute each for the encoder, with their own offsets each. I fixed it by instead creating one POSITION attribute with 3x the stride. I still have a bgr/rgb mixup somewhere but that's a minor issue.
![grafik](https://user-images.githubusercontent.com/36489576/219963155-9d7dc438-8a4b-4b47-9f94-d825533a1d0b.png)

I'm not sure if this is still worth an open ticket or not, since I am not sure which way of encoding separate x,y,z fields is the correct one. Please close if not.

**Comment by atteneder** [comment]
Glad you figured it out. I didn't know one could encode positions like that. Useful to know if someone gets into this trap again.
