### ISSUE TITLE
await async not working on android

### ISSUE THREAD

**Issue by busiyg** [atteneder/DracoUnity#58]
hey，bro，Thank you very much for your project，But I'm having some problems with it，project working on pc，but not on android，i find await async is not working on my android phone（android 13），did you work success on android？or any suggestion？

**Comment by atteneder** [comment]
@busiyg thanks bro.

What package version did you try?

**Comment by atteneder** [comment]
I've had time to test the upcoming version 5 on Android today....no problems whatsoever.

If you happen to provide reproduction steps (or a project), re-open or create a new issue.

Thanks!
