### ISSUE TITLE
DracoUnity crashes application on Magic Leap 2 (Android x86_64)

### ISSUE THREAD

**Issue by iweinbau** [atteneder/DracoUnity#59]
### Info
Application crashes after building simple Unity project to Magic Leap 2

Unity 2022.2.11
Magic leap SDK 1.5.0
DracoUnity 4.0.2

### Steps to reproduce

- Follow project setup on from the Magic Leap 2 documentation: https://developer-docs.magicleap.cloud/docs/guides/unity/getting-started/unity-getting-started

- Import DracoUnity
- Load bunny model from DracoUnityDemo
- Application crashes

2023/03/30 09:21:13.269 16746 16787 Error CRASH *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2023/03/30 09:21:13.269 16746 16787 Error CRASH Version '2022.2.11f1 (621cd60d08fd)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'x86_64'
2023/03/30 09:21:13.269 16746 16787 Error CRASH Build fingerprint: 'ml/demophon_aosp/demophon:10/B3E.230202.11-R.036/37:user/release-keys'
2023/03/30 09:21:13.269 16746 16787 Error CRASH Revision: '0'
2023/03/30 09:21:13.269 16746 16787 Error CRASH ABI: 'x86_64'
2023/03/30 09:21:13.269 16746 16787 Error CRASH Timestamp: 2023-03-30 09:21:13.269389476+0000
2023/03/30 09:21:13.269 16746 16787 Error CRASH pid: 16746, tid: 16787, name: Job.worker 1  >>> com.UnityTechnologies.com.unity.template.urpblank <<<
2023/03/30 09:21:13.269 16746 16787 Error CRASH uid: 10064
2023/03/30 09:21:13.269 16746 16787 Error CRASH signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr --------
2023/03/30 09:21:13.269 16746 16787 Error CRASH Cause: null pointer dereference
2023/03/30 09:21:13.269 16746 16787 Error CRASH     rax 00007f30b7574220  rbx 00007f310050fd80  rcx 00007f31a16ae958  rdx 00007f31a16ae960
2023/03/30 09:21:13.269 16746 16787 Error CRASH     r8  00007f31a16ae950  r9  0000000000000011  r10 00007f31eec6d400  r11 0000000000000246
2023/03/30 09:21:13.269 16746 16787 Error CRASH     r12 00007f30b7568cf0  r13 00007f31a16aea18  r14 00000000ffffffff  r15 00007f310050fd40
2023/03/30 09:21:13.269 16746 16787 Error CRASH     rdi 00007f30b553f020  rsi 000000000001a97c
2023/03/30 09:21:13.269 16746 16787 Error CRASH     rbp 00007f31a16ae970  rsp 00007f31a16ae948  rip 0000000000000000
2023/03/30 09:21:13.386 16746 16787 Error CRASH Forwarding signal 11
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of crash
2023/03/30 09:21:13.386 16746 16787 Fatal libc Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 16787 (Job.worker 1), pid 16746 (mplate.urpblank)
2023/03/30 09:21:13.423 16746 16829 Error AudioTrack AudioTrack callback unable to get output buffer, shouldn't happen!
2023/03/30 09:21:13.910 16746 16767 Error Unity [XR] MLInputStopControllerFeedback() failed with error MLResult_InvalidParam

**Comment by Babilinski** [comment]
@iweinbau make sure only the x86_64 plugin files are loading for that architecture. You can download the x86_64 version of the libraries here : https://github.com/Babilinski/draco/releases/tag/x86-64_build_01

**Comment by iweinbau** [comment]
@Babilinski thanks! I will try your build out as I was not able to make it work when building myself for x86_64. It still crashed on my magic leap 2
