### ISSUE TITLE
Crash when loading file at runtime (building library myself)

### ISSUE THREAD

**Issue by NumaNumaNuma** [atteneder/DracoUnity#60]
Hi,

Unity is crashing when loading a .drc file at runtime when compiling the draco decoder (mac bundle) myself (using your draco repo + your draco package from a local directory). I haven't changed a single thing to either repo yet.

I must be doing something wrong because everything works fine when using the package manager. 
Any help appreciated :) 
This is what I'm using:

- Unity 2021.3.22f1 - Apple Silicon
- atteneder/DracoUnity (latest main branch) - 655937bff22315b4851006ee2b1f9bb93dd19da6
- atteneder/draco (Unity 1.1.0 tag - 81afe07cbe2bd7b501d9c87a1e721fdc8fdbb07d
- ran cmake like this:

```
cmake ../ -G Xcode \
  -DDRACO_UNITY_PLUGIN=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CONFIGURATION_TYPES=Release \
  -DCMAKE_OSX_ARCHITECTURES=arm64\;x86_64
```

- built the dracodec_unity.bundle target from xcode (v14.3)
- replaced the local package .bundle in /plugins/x86_64 with the newly built one.
- I'm using the sample bunny file and the sample loading code

```
// Convert data to Unity mesh
var draco = new DracoMeshLoader();
// Async decoding has to start on the main thread and spawns multiple C# jobs.
var mesh = await draco.ConvertDracoMeshToUnity(data);
```

Unity crashes on this line:
`var jobHandle = JobHandle.CombineDependencies(jobHandles);`
DracoNative.cs line 486

Crash log is pretty unhelpful :D 

```
Out of memory!
Out of memory!
Cancelling DisplayDialog because it was run from a thread that is not the main thread: Fatal Error! Out of memory!

Cancelling DisplayDialog because it was run from a thread that is not the main thread: Fatal Error! Out of memory!

AcceleratorClientConnectionCallback - disconnected - :0
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
QObject: Cannot create children for a par
[dracodec_unity.bundle.zip](https://github.com/atteneder/DracoUnity/files/11189398/dracodec_unity.bundle.zip)
ent that is in a different thread.
(Parent is QObject(0x7ff062f8f7b0), parent's thread is QThread(0x7ff06380fc80), current thread is Thread(0x7ff062f28760)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QObject(0x7fc5723a8570), parent's thread is QThread(0x7fc572010860), current thread is Thread(0x7fc572039a90)
```

I have attached the binary I built too.
[dracodec_unity.bundle.zip](https://github.com/atteneder/DracoUnity/files/11195176/dracodec_unity.bundle.zip)

Thanks for your help!

**Comment by atteneder** [comment]
I think the latest main branch does not align with libraries 1.1.0. You'd need 2.0.0.

**Comment by atteneder** [comment]
Please transition to [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), the successor of this repository/package.
