### ISSUE TITLE
Support for Unity 2023.2+/Emscripten 3.1.38+

### ISSUE THREAD

**Issue by juj** [atteneder/DracoUnity#68]
Unity 2023.2 updates from Emscripten 3.1.8-unity to Emscripten 3.1.38-unity. One change between these upstream Emscripten versions is that the libstdcxx version bundled in Emscripten has been updated.

I tried building a test case, which I presume is the very one commented in https://github.com/atteneder/DracoUnity/issues/55#issuecomment-1628558572 , with latest Unity 2023.2, but it looks like the libstdcxx change brings in ABI breakages, then yielding new build errors

```
wasm-ld: error: DracoUnity/Runtime/Plugins/WebGL/libdracodec_unity.a(metadata.cc.o): undefined symbol: std::__2::__vector_base_common<true>::__throw_out_of_range() const
wasm-ld: error: DracoUnity/Runtime/Plugins/WebGL/libdracodec_unity.a(metadata.cc.o): undefined symbol: std::__2::__vector_base_common<true>::__throw_length_error() const
```

So it seems like a new DracoUnity version for 2023.2+ is needed.

I wonder if it would be possible to create a deployment where all google/draco code would be compiled directly as native C/C++ code inside Unity? Or I wonder if the draco build system needs are more complex that building as part of Unity's plugin build will not be feasible?

**Comment by atteneder** [comment]
fyi: There's a solution in the works. DracoUnity 5.x will put WebAssembly binaries in sub-packages that will match your Editor version. No promises, but ETA is 1-2 months.

**Comment by atteneder** [comment]
This is now supported by [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), the successor of this repository/package.
