### ISSUE TITLE
Can Point Cloud Color Information Be Imported At Runtime?

### ISSUE THREAD

**Issue by AbrarZShahriar** [atteneder/DracoUnity#69]
Can point cloud color information be imported at runtime if the point clouds are in .drc file format (not Draco compressed glTF point clouds)?

**Comment by dganzella** [comment]
yes

        async void convertDraco(string filepath)
        {
            var data = File.ReadAllBytes(filepath);

            var draco = new DracoMeshLoader();

            var mesh = await draco.ConvertDracoMeshToUnity(data);

            mesh.indexFormat = mesh.vertexCount > 65535 ?
                IndexFormat.UInt32 : IndexFormat.UInt16;

            mesh.SetIndices(
                Enumerable.Range(0, mesh.vertexCount).ToArray(),
                MeshTopology.Points, 0
            );

            mesh.UploadMeshData(true);

            setupPointCloud(mesh);
        }

        void setupPointCloud(Mesh mesh)
        {
            GameObject pointCloud = GameObject.CreatePrimitive(PrimitiveType.Cube);
            Destroy(pointCloud.GetComponent<Collider>());

            pointCloud.name = "My Draco";
            pointCloud.GetComponent<MeshFilter>().sharedMesh = mesh;

            Material m = Instantiate(pointCloudMaterial);
            m.SetFloat("_PointSize", .1f);
            pointCloud.GetComponent<MeshRenderer>().material = m;

        }

the point cloud material is from https://github.com/keijiro/Pcx/

**Comment by atteneder** [comment]
@dganzella thanks for the handy script.

This relates to the bug mentioned into #64

**Comment by atteneder** [comment]
Otherwise I think it's answered. Re-open if you disagree.
