### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by camroo29** [atteneder/DracoUnity#71]
Hi @atteneder,

I am trying to use DracoUnity with HoloLens. But the 3D model keeps disappearing. I believe that it is because of the FOV issue as mentioned [here](https://github.com/google/draco/issues/606).

So I tried the workaround solution you posted in [GitLab](https://gitlab.com/atteneder/DracoUnity/-/blob/main/Runtime/Scripts/DracoMeshLoader.cs?ref_type=heads). However, the application keeps crashing due to memory leak issue. I would like to know if there is any update regarding these issues.

Thanks

**Comment by atteneder** [comment]
Hi @camroo29 ,

Could you please check if the mesh's bounds are correct? It's possible that they're not and that causes Unity to cull the object too aggressively.

I'm not sure which workaround you're referring to (it links to an outdated `DracoMeshLoader.cs`, but I don't know what exactly you want to refer to). Are you saying that this workaround fixed the problem? Or that it introduced the memory leak? Or do you experience memory leaks in any case?

Thanks

**Comment by camroo29** [comment]
Hi @atteneder,

Thanks recalculating the bounds solved this issue. 

Actually, the outdated one solved the FOV issue but caused memory leaks. The current version doesn't cause memory leaks.

Thanks
