### ISSUE TITLE
Linux - Plugin 'libdracoenc_unity.so' is used from several locations

### ISSUE THREAD

**Issue by Ivolutio** [atteneder/DracoUnity#72]
When I try to build for Linux Standalone (x86_64) I get the following errors:
```Plugin 'libdracoenc_unity.so' is used from several locations:
 Packages/com.atteneder.draco/Runtime/Plugins/x86_64/libdracoenc_unity.so would be copied to <PluginPath>/libdracoenc_unity.so
 Packages/com.atteneder.draco/Runtime/Plugins/Android/libs/arm64-v8a/libdracoenc_unity.so would be copied to <PluginPath>/libdracoenc_unity.so
Please fix plugin settings and try again.

Plugins colliding with each other.
```

I installed DracoUnity using the installer, my manifest references `"com.atteneder.draco": "4.1.0"` 
Unity version 2020.3.26

I tested this in a clean project, also with Windows and Android build targets which both worked fine.

**Comment by Ivolutio** [comment]
I think PR #61 is related.

**Comment by atteneder** [comment]
Yes, looks like #61 will solve this. Thanks for your patience.

**Comment by atteneder** [comment]
This is now supported by [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), the successor of this repository/package.
