### ISSUE TITLE
Unity 2023.1 compatibility issues

### ISSUE THREAD

**Issue by robertdorn83** [atteneder/DracoUnity#73]
With Unity 2023.1 i get the following errors when importing a draco compressed glb file (with gltFast and UnityGltf):

![image](https://github.com/atteneder/DracoUnity/assets/118285915/7b107a76-cb9b-44af-a072-0054951f2ea5)

With Unity 2021 and 2022 it's working fine.

Example file:

[fox_draco.zip](https://github.com/atteneder/DracoUnity/files/13120582/fox_draco.zip)

**Comment by atteneder** [comment]
Thanks for reporting
What platform/operating system and version are you on?

**Comment by robertdorn83** [comment]
Windows 11 22H2

**Comment by atteneder** [comment]
I've opened a demo project in 2023.1 and indeed entering play mode gave me the same error (macOS here though).
Closing and re-opening the project solved it for me though 🤷 . Can you check that as well?
Have you tried running a build?

**Comment by robertdorn83** [comment]
Sorry for the late response...yeah...seems to work. On/Off for the win :D

**Comment by atteneder** [comment]
Thanks for the feedback.
Weird though. If it comes back, I'll have another look.
