### ISSUE TITLE
Tangent decoding support

### ISSUE THREAD

**Issue by robertdorn83** [atteneder/DracoUnity#74]
Currently only tangent calculation on import is supported.  

I'm not sure about the state of the "DRACO_TRANSCODER_SUPPORTED", but should not be an issue when using it for unity...?

![image](https://github.com/atteneder/DracoUnity/assets/118285915/771b1df0-a50c-49b7-8213-e317722a55d4)

**Comment by atteneder** [comment]
Yeah, this is not supported in current DracoUnity versions and likely won't be in 5.0.0 either.

What's your use-case? Would you know where to obtain test data for development?

Thanks

**Comment by robertdorn83** [comment]
Just working on UnityGltf, and found it when i tested some models :)

**Comment by atteneder** [comment]
This is now supported by [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), the successor of this repository/package.

Have a look at [`Draco.DracoDecoder.DecodeMesh`](https://docs.unity3d.com/Packages/com.unity.cloud.draco@5.0/api/Draco.DracoDecoder.DecodeMesh.html#Draco_DracoDecoder_DecodeMesh_UnityEngine_Mesh_MeshData_Unity_Collections_NativeSlice_System_Byte__Draco_DecodeSettings_System_Collections_Generic_Dictionary_UnityEngine_Rendering_VertexAttribute_System_Int32__) overloads with the `attributeIdMap` parameter.
