### ISSUE TITLE
ConditionalAttribute could not be found (com.unity.cloud.draco Package)

### ISSUE THREAD

**Issue by robertdorn83** [atteneder/DracoUnity#75]
![image](https://github.com/atteneder/DracoUnity/assets/118285915/b43135bf-d9d3-47a4-bde2-a604c6a1207b)

Hey, 
there is a "using System.Diagnostics; " missing :)

**Comment by atteneder** [comment]
Indeed :)
Please update to 5.0.1, that should fix it.

**Comment by robertdorn83** [comment]
oh...there was already an update :D  it totally missed that, sorry !
