### ISSUE TITLE
The 86x64 plugin isn't recognized in Unity (Unknown Architecture)

### ISSUE THREAD

**Issue by maramirez16** [atteneder/DracoUnity#76]
Good afternoon. I've imported Draco 4.1.0 in my Unity project, but upon doing so, this error is thrown:

DracoUnity-4.1.0/DracoUnity-4.1.0/Runtime/Plugins/x86_64/dracodec_unity.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.

The same thing happens with the dracoenc_unity.dll file in the same location. The Unity version I'm working with is 2021.3.16. Changing it into x86 within Unity didn't help, nor did changing the CPU into Any CPU.

How could I solve this issue? Could you help me with this problem, or upload a x64 version of the plugin?

**Comment by atteneder** [comment]
You've probably installed the package via GIT and did not properly fetch the GIT LFS files (which the DLLs are).

Please install the recommended (see the README about that).

Even better: switch to [Draco for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/), which was already updated to version 5.0.2.

hth
