### ISSUE TITLE
Unknown reason: Unable to load my file

### ISSUE THREAD

**Issue by Dobmod** [atteneder/DracoUnity#77]
Hello,
Atteneder
Due to some uncontrollable reasons, I had to use the old version of Unity (2019.3.15f1) for development. When I used this library (3.3.2) to load my own model, the method returned null. But when I used a model from the official draco repository (such as car.drc), I succeeded. This is strange, I don't know the reason behind it. My model was converted from stl format using draco version 1.5.6. It is normal for me to load these models using three.js and draco_decoder.js on the webpage. Hopefully you know reason, Thanks.
[My Model And Car Model.zip](https://github.com/atteneder/DracoUnity/files/15063365/My.Model.And.Car.Model.zip)

**Comment by Dobmod** [comment]
When I downgraded to version 3.0.2 and resolved this issue, everything was fine.

**Comment by atteneder** [comment]
Glad you got it resolved!

I can reproduce the issue. When I try to decode it with `draco_decoder` I get the following error:

```bash
draco_decoder -i test.drc -o test.obj
Failed to decode the input file Unsupported major version.

**Comment by atteneder** [comment]
So the question becomes: How did you create this model and with what software (version)?
