### ISSUE TITLE
Code signing error on upload to Mac Apple Store

### ISSUE THREAD

**Issue by leonardoscapolan** [atteneder/DracoUnity#78]
When trying to upload a build with the latest version of the package (5.1.5), the following issues are raised:

Asset validation failed (90334)
Invalid Code Signature Identifier. The identifier "draco_unity" in your code signature for "draco_unity" must match its Bundle Identifier "$bundleIdentifier" (ID:  \*\*\*)
 
Asset validation failed (90276)
Missing Bundle Identifier. The application bundle contains a tool or framework [\*\*\*.pkg/Payload/\*\*\*.app/Contents/PlugIns/draco_unity.bundle] that is missing the bundle identifier in its Info.plist file. (ID: \*\*\*)

**Comment by atteneder** [comment]
Thanks for reporting.

I'm already investigating the fix for it.

Related issue in [glTFast](https://github.com/atteneder/glTFast/issues/712).

**Comment by leonardoscapolan** [comment]
Thanks for the fast reply, hope all goes well

**Comment by atteneder** [comment]
Fix landed in [Draco for Unity 5.1.6](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/).
