### ISSUE TITLE
GLIBC_2.29 not found 

### ISSUE THREAD

**Issue by Blocovin** [atteneder/DracoUnity#8]
Hi,

We use [unityci/editor:2019.4.21f1-base-0.10](https://hub.docker.com/layers/unityci/editor/2019.4.21f1-base-0.10/images/sha256-05bdc8dbf30b0e08ec435624a646f94d523964d27948796d4b88d86724a64264?context=explore) in our automated test CI and we got this error :

```console
Plugins: Couldn't open XXX/Library/PackageCache/com.atteneder.draco@1.4.0/Runtime/Plugins/x86_64/libdracodec_unity.so,
error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by XXX/Library/PackageCache/com.atteneder.draco@1.4.0/Runtime/Plugins/x86_64/libdracodec_unity.so)
```

The docker image is based on `18.04.5 LTS (Bionic Beaver)` which contain `GLIBC 2.27`.

Could it be possible to build `libdracodec_unity.so` with `GLIBC 2.27` ?

**Comment by atteneder** [comment]
Hi @Blocovin,

Thanks for the detailed report! I built the library via GitHub actions' virtual environment `ubuntu-20.04`. I started an attempt to build with `ubuntu-18.04`. If you want to, go ahead and test the library. You should be able to download the artifacts here:

<https://github.com/atteneder/draco/actions/runs/625090681>

Let me know if it works.

**Comment by Blocovin** [comment]
Thank you for your solution !

I didn't seen your draco repository with GitHub actions :satisfied:

I tried to move `com.atteneder.draco@1.4.0` from unity package cache into Assets folder and replaced `libdracodec_unity.so` by `.so` contains in github actions result.
And I add `DRACO_UNITY` in `Scripting Define Symbols`but it doesn't work.

```
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libAssets/Packages/com.atteneder.draco@1.4.0/Runtime/Plugins/x86_64/libdracodec_unity.so
```

I think I'm doing something wrong ?

For more information, we use latest unity LTS for our production app (2019.4.21f1 LTS).
Officially supported ubuntu version for Unity 2019.4.21f1 LTS is is still 18.04.
Ubuntu 20 is officially supported by Unity 2020.2.

Discussion about it from [game-ci](https://github.com/game-ci/docker/issues/72#issuecomment-774578592).

**Comment by atteneder** [comment]
Oh sorry. Those libs are meant for version 2.0.0-preview :/
I have to build the current branch (`legacy/unity-1`) as well with ubuntu 18.04

**Comment by Blocovin** [comment]
Thank you very much !
I fork and I build legacy branch `legacy/unity-1`.
So now our test CI work perfecty with draco ❤️
