### ISSUE TITLE
Supporting Point Cloud (PLY little endian binary)

### ISSUE THREAD

**Issue by taehongjeong** [atteneder/DracoUnity#9]
Hi! Thank you for your great work.

For fun, I'd like to implement point cloud support.

May I ask you have a plan for it?

**Comment by atteneder** [comment]
Hi @taehongjeong ,

Thanks for reaching out. Point cloud support is an excellent idea. Although I never needed it, some folks definitely do.

Have a look at [the work](https://github.com/atteneder/glTFast/issues/135) @camnewnham already did.

The only reason I haven't reviewed it yet is that his work is based on DracoUnit 1.4 while I was doing 2.0 in parallel (which has a completely renewed native draco integration.

Version 2.0 is currently blocked by an issue (bone joints and weights aren't working). The solution is being worked on.

The best way to help would be to look into rebasing Cameron's work on DracoUnity 2.0.0-preview, as it will be released hopefully soon.

Kind regards,
Andi

**Comment by taehongjeong** [comment]
Hi Andi,

Thank you so much for your kind guidance!

Let me see what you suggested and make progress.

Best,
Hugh
